// Generated by gencpp from file mesh80211s/MeshStations.msg
// DO NOT EDIT!


#ifndef MESH80211S_MESSAGE_MESHSTATIONS_H
#define MESH80211S_MESSAGE_MESHSTATIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mesh80211s/MeshStation.h>

namespace mesh80211s
{
template <class ContainerAllocator>
struct MeshStations_
{
  typedef MeshStations_<ContainerAllocator> Type;

  MeshStations_()
    : header()
    , stations()  {
    }
  MeshStations_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mesh80211s::MeshStation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mesh80211s::MeshStation_<ContainerAllocator> >> _stations_type;
  _stations_type stations;





  typedef boost::shared_ptr< ::mesh80211s::MeshStations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mesh80211s::MeshStations_<ContainerAllocator> const> ConstPtr;

}; // struct MeshStations_

typedef ::mesh80211s::MeshStations_<std::allocator<void> > MeshStations;

typedef boost::shared_ptr< ::mesh80211s::MeshStations > MeshStationsPtr;
typedef boost::shared_ptr< ::mesh80211s::MeshStations const> MeshStationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mesh80211s::MeshStations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mesh80211s::MeshStations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mesh80211s::MeshStations_<ContainerAllocator1> & lhs, const ::mesh80211s::MeshStations_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.stations == rhs.stations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mesh80211s::MeshStations_<ContainerAllocator1> & lhs, const ::mesh80211s::MeshStations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mesh80211s

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mesh80211s::MeshStations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mesh80211s::MeshStations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mesh80211s::MeshStations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mesh80211s::MeshStations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mesh80211s::MeshStations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mesh80211s::MeshStations_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mesh80211s::MeshStations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa4702b9dc887621257c88e89f258184";
  }

  static const char* value(const ::mesh80211s::MeshStations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa4702b9dc887621ULL;
  static const uint64_t static_value2 = 0x257c88e89f258184ULL;
};

template<class ContainerAllocator>
struct DataType< ::mesh80211s::MeshStations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mesh80211s/MeshStations";
  }

  static const char* value(const ::mesh80211s::MeshStations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mesh80211s::MeshStations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"mesh80211s/MeshStation[] stations\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mesh80211s/MeshStation\n"
"string mac\n"
"string device\n"
"uint32 inactive_time\n"
"uint32 rx_bytes\n"
"uint32 rx_packets\n"
"uint32 tx_bytes\n"
"uint32 tx_packets\n"
"int32 signal\n"
"uint16 tx_bitrate\n"
"uint16 llid\n"
"uint16 plid\n"
"string plink\n"
;
  }

  static const char* value(const ::mesh80211s::MeshStations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mesh80211s::MeshStations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MeshStations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mesh80211s::MeshStations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mesh80211s::MeshStations_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stations[]" << std::endl;
    for (size_t i = 0; i < v.stations.size(); ++i)
    {
      s << indent << "  stations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mesh80211s::MeshStation_<ContainerAllocator> >::stream(s, indent + "    ", v.stations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESH80211S_MESSAGE_MESHSTATIONS_H
