// Generated by gencpp from file laser_simulator/PoseStampedNamedArray.msg
// DO NOT EDIT!


#ifndef LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMEDARRAY_H
#define LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMEDARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <laser_simulator/PoseStampedNamed.h>

namespace laser_simulator
{
template <class ContainerAllocator>
struct PoseStampedNamedArray_
{
  typedef PoseStampedNamedArray_<ContainerAllocator> Type;

  PoseStampedNamedArray_()
    : poses()  {
    }
  PoseStampedNamedArray_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedNamedArray_

typedef ::laser_simulator::PoseStampedNamedArray_<std::allocator<void> > PoseStampedNamedArray;

typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamedArray > PoseStampedNamedArrayPtr;
typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamedArray const> PoseStampedNamedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator1> & lhs, const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator2> & rhs)
{
  return lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator1> & lhs, const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b8df607d1aa74fc669faf952f38163b";
  }

  static const char* value(const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b8df607d1aa74fcULL;
  static const uint64_t static_value2 = 0x669faf952f38163bULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_simulator/PoseStampedNamedArray";
  }

  static const char* value(const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_simulator/PoseStampedNamed[] poses\n"
"\n"
"================================================================================\n"
"MSG: laser_simulator/PoseStampedNamed\n"
"std_msgs/Header header\n"
"string child_frame_id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedNamedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_simulator::PoseStampedNamedArray_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMEDARRAY_H
