// Generated by gencpp from file laser_simulator/PoseStampedNamed.msg
// DO NOT EDIT!


#ifndef LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMED_H
#define LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace laser_simulator
{
template <class ContainerAllocator>
struct PoseStampedNamed_
{
  typedef PoseStampedNamed_<ContainerAllocator> Type;

  PoseStampedNamed_()
    : header()
    , child_frame_id()
    , pose()  {
    }
  PoseStampedNamed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , child_frame_id(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedNamed_

typedef ::laser_simulator::PoseStampedNamed_<std::allocator<void> > PoseStampedNamed;

typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamed > PoseStampedNamedPtr;
typedef boost::shared_ptr< ::laser_simulator::PoseStampedNamed const> PoseStampedNamedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_simulator::PoseStampedNamed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_simulator::PoseStampedNamed_<ContainerAllocator1> & lhs, const ::laser_simulator::PoseStampedNamed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.child_frame_id == rhs.child_frame_id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_simulator::PoseStampedNamed_<ContainerAllocator1> & lhs, const ::laser_simulator::PoseStampedNamed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59fe069757a09d1537dfce96b120a364";
  }

  static const char* value(const ::laser_simulator::PoseStampedNamed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59fe069757a09d15ULL;
  static const uint64_t static_value2 = 0x37dfce96b120a364ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_simulator/PoseStampedNamed";
  }

  static const char* value(const ::laser_simulator::PoseStampedNamed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string child_frame_id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::laser_simulator::PoseStampedNamed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedNamed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_simulator::PoseStampedNamed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_simulator::PoseStampedNamed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.child_frame_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SIMULATOR_MESSAGE_POSESTAMPEDNAMED_H
