// Generated by gencpp from file laser_simulator/ScanPair.msg
// DO NOT EDIT!


#ifndef LASER_SIMULATOR_MESSAGE_SCANPAIR_H
#define LASER_SIMULATOR_MESSAGE_SCANPAIR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/LaserScan.h>
#include <sensor_msgs/LaserScan.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Transform.h>

namespace laser_simulator
{
template <class ContainerAllocator>
struct ScanPair_
{
  typedef ScanPair_<ContainerAllocator> Type;

  ScanPair_()
    : scan1()
    , scan2()
    , pose1()
    , pose2()
    , transform()  {
    }
  ScanPair_(const ContainerAllocator& _alloc)
    : scan1(_alloc)
    , scan2(_alloc)
    , pose1(_alloc)
    , pose2(_alloc)
    , transform(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan1_type;
  _scan1_type scan1;

   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _scan2_type;
  _scan2_type scan2;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose1_type;
  _pose1_type pose1;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose2_type;
  _pose2_type pose2;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _transform_type;
  _transform_type transform;





  typedef boost::shared_ptr< ::laser_simulator::ScanPair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_simulator::ScanPair_<ContainerAllocator> const> ConstPtr;

}; // struct ScanPair_

typedef ::laser_simulator::ScanPair_<std::allocator<void> > ScanPair;

typedef boost::shared_ptr< ::laser_simulator::ScanPair > ScanPairPtr;
typedef boost::shared_ptr< ::laser_simulator::ScanPair const> ScanPairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_simulator::ScanPair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_simulator::ScanPair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::laser_simulator::ScanPair_<ContainerAllocator1> & lhs, const ::laser_simulator::ScanPair_<ContainerAllocator2> & rhs)
{
  return lhs.scan1 == rhs.scan1 &&
    lhs.scan2 == rhs.scan2 &&
    lhs.pose1 == rhs.pose1 &&
    lhs.pose2 == rhs.pose2 &&
    lhs.transform == rhs.transform;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::laser_simulator::ScanPair_<ContainerAllocator1> & lhs, const ::laser_simulator::ScanPair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace laser_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::ScanPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_simulator::ScanPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::ScanPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_simulator::ScanPair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::ScanPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_simulator::ScanPair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_simulator::ScanPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b8f9cfc12d41180f8cbbd1515a00b5e";
  }

  static const char* value(const ::laser_simulator::ScanPair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b8f9cfc12d41180ULL;
  static const uint64_t static_value2 = 0xf8cbbd1515a00b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_simulator::ScanPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_simulator/ScanPair";
  }

  static const char* value(const ::laser_simulator::ScanPair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_simulator::ScanPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/LaserScan scan1 \n"
"sensor_msgs/LaserScan scan2\n"
"geometry_msgs/Pose pose1\n"
"geometry_msgs/Pose pose2\n"
"geometry_msgs/Transform transform # Transformation from scan1 to scan2\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::laser_simulator::ScanPair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_simulator::ScanPair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scan1);
      stream.next(m.scan2);
      stream.next(m.pose1);
      stream.next(m.pose2);
      stream.next(m.transform);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanPair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_simulator::ScanPair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_simulator::ScanPair_<ContainerAllocator>& v)
  {
    s << indent << "scan1: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan1);
    s << indent << "scan2: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.scan2);
    s << indent << "pose1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose1);
    s << indent << "pose2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose2);
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SIMULATOR_MESSAGE_SCANPAIR_H
