// Generated by gencpp from file scarab_msgs/MoveResult.msg
// DO NOT EDIT!


#ifndef SCARAB_MSGS_MESSAGE_MOVERESULT_H
#define SCARAB_MSGS_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scarab_msgs
{
template <class ContainerAllocator>
struct MoveResult_
{
  typedef MoveResult_<ContainerAllocator> Type;

  MoveResult_()
    : final_status(0)  {
    }
  MoveResult_(const ContainerAllocator& _alloc)
    : final_status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _final_status_type;
  _final_status_type final_status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FINISHED)
  #undef FINISHED
#endif
#if defined(_WIN32) && defined(TIMEOUT)
  #undef TIMEOUT
#endif
#if defined(_WIN32) && defined(STUCK)
  #undef STUCK
#endif
#if defined(_WIN32) && defined(NOTREADY)
  #undef NOTREADY
#endif
#if defined(_WIN32) && defined(UNREACHABLE)
  #undef UNREACHABLE
#endif

  enum {
    FINISHED = 0u,
    TIMEOUT = 1u,
    STUCK = 2u,
    NOTREADY = 3u,
    UNREACHABLE = 4u,
  };


  typedef boost::shared_ptr< ::scarab_msgs::MoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scarab_msgs::MoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResult_

typedef ::scarab_msgs::MoveResult_<std::allocator<void> > MoveResult;

typedef boost::shared_ptr< ::scarab_msgs::MoveResult > MoveResultPtr;
typedef boost::shared_ptr< ::scarab_msgs::MoveResult const> MoveResultConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scarab_msgs::MoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scarab_msgs::MoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scarab_msgs::MoveResult_<ContainerAllocator1> & lhs, const ::scarab_msgs::MoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_status == rhs.final_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scarab_msgs::MoveResult_<ContainerAllocator1> & lhs, const ::scarab_msgs::MoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scarab_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scarab_msgs::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scarab_msgs::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scarab_msgs::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scarab_msgs::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scarab_msgs::MoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scarab_msgs::MoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scarab_msgs::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79b09be8622e2706904a1b48e955dad6";
  }

  static const char* value(const ::scarab_msgs::MoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79b09be8622e2706ULL;
  static const uint64_t static_value2 = 0x904a1b48e955dad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::scarab_msgs::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scarab_msgs/MoveResult";
  }

  static const char* value(const ::scarab_msgs::MoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scarab_msgs::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 FINISHED=0      # Successfully reached goal\n"
"uint8 TIMEOUT=1       # Took too long to reach goal\n"
"uint8 STUCK=2         # Robot has not moved in a while\n"
"uint8 NOTREADY=3      # Don't have all the data we need to move, check back soon!\n"
"uint8 UNREACHABLE=4   # Goal is no longer reachable (e.g., due to map change)\n"
"\n"
"uint8 final_status    # Status of robot when action was ended\n"
;
  }

  static const char* value(const ::scarab_msgs::MoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scarab_msgs::MoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scarab_msgs::MoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scarab_msgs::MoveResult_<ContainerAllocator>& v)
  {
    s << indent << "final_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.final_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARAB_MSGS_MESSAGE_MOVERESULT_H
